# -*- coding: utf-8 -*-
"""01 Fun Sample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_uwxKTYuhIBSfXFKgYdTUpLh7wVuLSL
"""

price_per_share = 215
num_of_shares=1000

type(price_per_share)
market_cap=price_per_share*num_of_shares;

def calculate_market_cap(price_per_share: int,num_of_shares: int) -> int:
  market_cap=price_per_share*num_of_shares
  return market_cap

calculate_market_cap(215,1000)

