# -*- coding: utf-8 -*-
"""01_python_fileRead.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ac-lQRzTrR_HSM8NPWMM02S3jJIsRmZ3

# **🐍 Intro to Python: Ch 2**

---
## **Financial Ratios from CSV 📈**

### **Concepts**
- Reading & writing CSV files with the `csv` module  
- `pathlib.Path` for file handling  
- Computing **Price-to-Book** and **P/E** ratios

| Ratio | Formula |
|-------|---------|
| Price-to-Book | Price ÷ Book Value per Share |
| P/E Ratio | Price ÷ Earnings per Share (EPS) |

### **2.0 Upload files to colab**
"""

from google.colab import files

# This will prompt you to select the file from your local machine. Upload in.csv.
uploaded = files.upload()

import io

filename = list(uploaded.keys())[0]
CSV_DATA = uploaded[filename].decode("utf-8")

print(f"✅ Loaded '{filename}'")
print(CSV_DATA[:300])

"""### **2.2 The `safe_ratio` helper**"""

def safe_ratio(numerator: str, denominator: str) -> float | str:
    """Return numerator/denominator, or '' if invalid (zero division, bad type)."""
    try:
        num = float(numerator)
        den = float(denominator)
        if den == 0:
            return ""
        return round(num / den, 6)
    except (TypeError, ValueError):
        return ""

# Quick test
print(safe_ratio("2850.50", "3.2"))   # expected: 890.78125
print(safe_ratio("100", "0"))         # expected: ''
print(safe_ratio("abc", "3"))         # expected: ''

"""### **2.3 Process the uploaded CSV**"""

import csv, io

rows = []
reader = csv.DictReader(io.StringIO(CSV_DATA))

for row in reader:
    row["price_to_book_ratio"] = safe_ratio(row["price"], row["book_ratio"])
    row["pe_ratio"]            = safe_ratio(row["price"], row["eps"])
    rows.append(row)

# Pretty-print
header = f"{'Ticker':<8} {'P/B':>12} {'P/E':>12}"
print(header)
print("-" * len(header))
for r in rows:
    print(f"{r['ticker']:<8} {str(r['price_to_book_ratio']):>12} {str(r['pe_ratio']):>12}")

"""### **2.4 ✏️ Exercises**
1. Which stock has the **highest P/E ratio**? What does that imply?
2. Add a `dividend_yield` column: assume dividend = `price × 0.02` and yield = `dividend ÷ price`.
3. Write the results out to a real CSV file using `csv.DictWriter`.
"""

# Your code here

"""### **Exercise 1: Which stock has the highest P/E ratio? What does that imply?**"""

highest_pe_stock = None
max_pe_ratio = -1

for row in rows:
    pe_ratio = row.get('pe_ratio')
    if pe_ratio and isinstance(pe_ratio, (int, float)) and pe_ratio > max_pe_ratio:
        max_pe_ratio = pe_ratio
        highest_pe_stock = row['ticker']

if highest_pe_stock:
    print(f"The stock with the highest P/E ratio is {highest_pe_stock} with a P/E ratio of {max_pe_ratio:.2f}.")
    print("\nA high P/E ratio often implies that investors expect higher earnings growth in the future compared to companies with lower P/E ratios. It can also suggest that the stock is overvalued, or that it is a growth stock with high potential.")
else:
    print("Could not determine the stock with the highest P/E ratio. Please ensure 'pe_ratio' is correctly calculated and is a numeric type.")

"""### **Exercise 2: Add a `dividend_yield` column**"""

for row in rows:
    try:
        # As per the prompt: dividend = price * 0.02 and yield = dividend / price
        # This simplifies to dividend_yield = 0.02 (assuming price is not zero)
        # However, it's more robust to calculate based on price if it varies.
        price = float(row['price'])
        if price != 0:
            dividend = price * 0.02
            row['dividend_yield'] = round(dividend / price, 4) # Yield is typically represented as a percentage or a decimal
        else:
            row['dividend_yield'] = ""
    except (ValueError, KeyError):
        row['dividend_yield'] = ""

# Display a sample of rows with the new column
print("Rows with 'dividend_yield' column:")
# Create a dynamic header to include the new column
if rows:
    header_keys = list(rows[0].keys())
    # Adjust width for better printing
    header_str = f"{header_keys[0]:<8}"
    for key in header_keys[1:]:
        header_str += f" {key:>12}"
    print(header_str)
    print("-" * len(header_str))
    for r in rows[:5]: # Display first 5 rows
        row_str = f"{r[header_keys[0]]:<8}"
        for key in header_keys[1:]:
            value = r[key]
            # Handle float values for formatting
            if isinstance(value, float):
                row_str += f" {value:>12.4f}"
            else:
                row_str += f" {str(value):>12}"
        print(row_str)

"""### **Exercise 3: Write the results out to a real CSV file using `csv.DictWriter`**"""

import csv

# Define the output filename
output_filename = 'out.csv'

# Ensure rows is not empty to get header
if rows:
    # Get all unique headers from the first row (assuming all rows have the same keys)
    fieldnames = list(rows[0].keys())

    with open(output_filename, 'w', newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        # Write the header row
        writer.writeheader()

        # Write all data rows
        writer.writerows(rows)

    print(f"✅ Successfully wrote data to '{output_filename}'")

    # Optional: Display the content of the created CSV file
    with open(output_filename, 'r') as f:
        print("\nContent of 'out.csv':")
        print(f.read())
else:
    print("No data to write to CSV.")