# -*- coding: utf-8 -*-
"""01_python_ch_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJEwK5aEhdDLboZqH6IaCqOWeaflZA2C

# **🐍 Intro to Python: Ch 3**

---
## **Object-Oriented Programming 🏗️**

### Concepts
- Classes and `__init__`  
- Instance methods vs `@staticmethod`  
- Encapsulation: bundling data + behaviour together

We refactor the Chapter 2 code into a `RatioCalculator` class.

### **3.1 The `RatioCalculator` class**
"""

import csv, io
from typing import Dict, List


class RatioCalculator:
    """Reads stock data and computes financial ratios."""

    def __init__(self, raw_csv: str) -> None:
        self.raw_csv = raw_csv

    @staticmethod
    def safe_ratio(numerator: str, denominator: str) -> float | str:
        """Return numerator/denominator as float, or '' if invalid."""
        try:
            num = float(numerator)
            den = float(denominator)
            if den == 0:
                return ""
            return round(num / den, 6)
        except (TypeError, ValueError):
            return ""

    def calculate_row(self, row: Dict[str, str]) -> Dict[str, str]:
        row["price_to_book_ratio"] = self.safe_ratio(row.get("price", ""), row.get("book_ratio", ""))
        row["pe_ratio"]            = self.safe_ratio(row.get("price", ""), row.get("eps", ""))
        return row

    def run(self) -> List[Dict]:
        reader = csv.DictReader(io.StringIO(self.raw_csv))
        return [self.calculate_row(row) for row in reader]

"""### **3.2 Use the class**"""

from google.colab import files

# Upload in.csv
uploaded = files.upload()

import io

filename = list(uploaded.keys())[0]
CSV_DATA = uploaded[filename].decode("utf-8")

print(f"✅ Loaded '{filename}' for Chapter 3")

calc    = RatioCalculator(CSV_DATA)
results = calc.run()

for r in results:
    print(f"{r['ticker']:<8}  P/B={r['price_to_book_ratio']:>12}  P/E={r['pe_ratio']:>12}")

"""### **3.3 Key differences vs Chapter 2**

| Procedural (Ch 2) | OOP (Ch 3) |
|---|---|
| `safe_ratio()` is a free function | `safe_ratio()` is a `@staticmethod` on the class |
| Logic spread across functions | Bundled inside `RatioCalculator` |
| Hard to reuse / test in isolation | Easy to instantiate with different data |

### **3.4 ✏️ Exercises**
1. Add a `best_value_stock()` method that returns the ticker with the lowest P/B ratio.
2. Add a `__repr__` method so `print(calc)` shows something meaningful.
3. Subclass `RatioCalculator` to create `ExtendedRatioCalculator` that also computes P/S ratio (assume `revenue_per_share` column exists).
"""

# Your code here